### ISSUE TITLE
Setting up ChatGPT api

### ISSUE THREAD

**Issue by conxant0** [rokkunbruv/bill-splitter-web-app#3]
- [ ] Create a New Folder for Services:
       - [ ] Create a file file named chatgptService.js where you will write the logic for sending the image to ChatGPT and parsing the response.
- [ ] Update Controllers
- [ ] Define Routes
- [ ] Create folder in frontend to receive api calls
- [ ] Update components to allow users to upload receipt image
- [ ] State Management:

**Comment by eliseoalcaraz** [comment]
> * [ ]  Create a New Folder for Services:
>   - [ ] Create a file file named chatgptService.js where you will write the logic for sending the image to ChatGPT and parsing the response.
> * [ ]  Update Controllers
> * [ ]  Define Routes
> * [ ]  Create folder in frontend to receive api calls
> * [ ]  Update components to allow users to upload receipt image
> * [ ]  State Management:
